export const SPLIT_CONTRACT_FACTORY_ADDRESS = 'KT1DoyD6kr8yLK8mRBFusyKYJUk2ZxNHKP1N';
export const SIGN_CONTRACT_ADDRESS = 'KT1BcLnWRziLDNJNRn3phAANKrEBiXhytsMY';
export const HEN_CONTRACT_FA2 = 'KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton';
export const HEN_CONTRACT_MARKETPLACE = 'KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9';
export const HEN_SUBJKT_REGISTRY_ADDRESS = 'KT1My1wDZHDGweCrJnQJi3wcFaS67iksirvj';
