export const HEN_CONTRACT_FA2 = 'KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton';
export const HEN_CONTRACT_MARKETPLACE = 'KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9';
export const HEN_CONTRACT_MARKETPLACE_V2 = 'KT1HbQepzV1nVGg8QVznG7z4RcHseD5kwqBn';

export const TEIA_CONTRACT_MARKETPLACE = 'KT1PHubm9HtyQEJ4BBpMTVomq6mhbfNZ9z5w';

export const OBJKT_CONTRACT_MARKETPLACE = 'KT1FvqJwEDWb1Gwc55Jd1jjTHRVWbYKUUpyq';
export const OBJKT_CONTRACT_MARKETPLACE_V2 = 'KT1WvzYHCNBvDSdwafTHv7nJ1dWmZ8GCYuuC';
export const OBJKT_CONTRACT_MINTING_FACTORY = 'KT1Aq4wWmVanpQhq4TTfjZXB5AjFpx15iQMM';

export const OBJKT_CONTRACT_ENGLISH_AUCTION_PRE = 'KT1Wvk8fon9SgNEPQKewoSL2ziGGuCQebqZc';
export const OBJKT_CONTRACT_ENGLISH_AUCTION_V1 = 'KT1XjcRq5MLAzMKQ3UHsrue2SeU2NbxUrzmU';
export const OBJKT_CONTRACT_ENGLISH_AUCTION_V2 = 'KT18p94vjkkHYY3nPmernmgVR7HdZFzE7NAk';

export const OBJKT_CONTRACT_DUTCH_AUCTION_PRE = 'KT1ET45vnyEFMLS9wX1dYHEs9aCN3twDEiQw';
export const OBJKT_CONTRACT_DUTCH_AUCTION_V1 = 'KT1QJ71jypKGgyTNtXjkCAYJZNhCKWiHuT2r';
export const OBJKT_CONTRACT_DUTCH_AUCTION_V2 = 'KT1XXu88HkNzQRHNgAf7Mnq68LyS9MZJNoHP';

export const FX_CONTRACT_FA2 = 'KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE';
export const FX_CONTRACT_MARKETPLACE = 'KT1Xo5B7PNBAeynZPmca4bRh6LQow4og1Zb9';
export const FX_CONTRACT_MINT = 'KT1AEVuykWeuuFX7QkEAMNtffzwhe1Z98hJS';
export const FX_CONTRACT_MINT_V2 = 'KT1XCoGnfupWk7Sp8536EfrxcP73LmT68Nyr';

export const FX_CONTRACT_FA2_V3 = 'KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi';
export const FX_CONTRACT_MINT_V3 = 'KT1BJC12dG17CVvPKJ1VYaNnaT5mzfnUTwXv';
export const FX_CONTRACT_MARKETPLACE_V3 = 'KT1GbyoDi7H1sfXmimXpptZJuCdHMh66WS9u';

export const VERSUM_CONTRACT_FA2 = 'KT1LjmAdYQCLBjwv4S2oFkEzyHVkomAf5MrW';
export const VERSUM_CONTRACT_MARKETPLACE = 'KT1GyRAJNdizF1nojQz62uGYkx8WFRUJm9X5';

export const EIGHTBIDOU_8X8_COLOR_CONTRACT_FA2 = 'KT1MxDwChiDwd6WBVs24g1NjERUoK622ZEFp';
export const EIGHTBIDOU_8X8_COLOR_CONTRACT_MARKETPLACE = 'KT1BvWGFENd4CXW5F3u4n31xKfJhmBGipoqF';

export const EIGHTBIDOU_24X24_MONOCHROME_CONTRACT_FA2 = 'KT1TR1ErEQPTdtaJ7hbvKTJSa1tsGnHGZTpf';
export const EIGHTBIDOU_24X24_MONOCHROME_CONTRACT_MARKETPLACE = 'KT1AHBvSo828QwscsjDjeUuep7MgApi8hXqA';

export const EIGHTBIDOU_24X24_COLOR_CONTRACT_FA2 = 'KT1VikAWA8wQHLZgHoAGL7Z9kCjgbCEnvWA3';
export const EIGHTBIDOU_24X24_COLOR_CONTRACT_MARKETPLACE = 'KT1QtnHR8p2hBjUhPRy9BCWgy7s7L578PA7N';

export const TYPED_CONTRACT_MINT = 'KT1CK9RnWZGnejBeT6gJfgvf4p7f1NwhP9wS';
export const TYPED_CONTRACT_MARKETPLACE = 'KT1VoZeuBMJF6vxtLqEFMoc4no5VDG789D7z';
export const TYPED_CONTRACT_FA2 = 'KT1J6NY5AU61GzUX51n59wwiZcGJ9DrNTwbK';

export const HAIKU_CONTRACT_MARKETPLACE = 'KT19vw7kh7dzTRxFUZNWu39773baauzNWtzj';
export const HAIKU_CONTRACT_FA2 = 'KT1Aq1umaV8gcDQmi4CLDk7KeKpoUjFQeg1B';

export const BURN_ADDRESS = 'tz1burnburnburnburnburnburnburjAYjjX';

export const POSTGRES_ERROR_CODE_UNIQUE_VIOLATION = '23505';

export const SALE_INTERFACE = 'SALE';

export const CURRENCY_MAPPINGS: Record<string, string> = {
  KT1TjnZYs5CGLbmV6yuW169P8Pnr9BiVwwjz: 'otez',
};

export const GENTK_VERSION_TO_FA2_CONTRACT_MAPPING: Record<string, string> = {
  '0': 'KT1KEa8z6vWXDJrVqtMrAeDVzsvxat3kHaCE',
  '1': 'KT1U6EHmNxJTkvaWJ4ThczG4FSDaHC21ssvi',
};
